# Generated by Django 4.2.3 on 2023-07-09 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_rename_listings_watchlist_listing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='lid',
            new_name='listing',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='lid',
            new_name='listing',
        ),
    ]
